name: weather_app
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  get: ^4.6.6
  intl: ^0.18.1
  http: ^1.1.0
  sleek_circular_slider: ^2.0.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/weather/
    - .env
